### PR TITLE
Major updates

### PR DESCRIPTION
**Pull request by gstroup**
* rebuilt from recent yeoman generator. 
* fixed integration with userinfo endpoint. 
* decoupled from px-app-nav.  
* no longer showing custom menu items.

@mdwragg @randyaskin Please take a look when you have the chance.  Thanks.

### CODE REVIEW

**Comment by gstroup** [comment]
tests passing now.  any thoughts on merging this??

**Comment by randyaskin** [comment]
Hey Greg, do you think it makes sense to leave the expand/collapse behavior in there, so that it *could* still be used with px-app-nav, but doesn't have to be? Also curious whether we still need the custom menu items - honestly no idea how actual teams are using this component.

**Comment by gstroup** [comment]
Thanks for reviewing.  In an earlier conversation with @mdwragg and @gedesigntech I thought they wanted to de-couple this component from the px-app-nav.  But if you guys would like to keep the expand/collapse behavior, let me know, and I'll add it back in.  I was also not sure about the custom menu items... I haven't seen people using them, but maybe some people do use them.  I left them out just to simplify, but I could add those back in without too much trouble.  I did review this with Hans, and he approved.  Martin?  What do you think?

**Comment by gstroup** [comment]
Had a meeting with Hans & Ken.  Implemented all the changes they requested.

* allow words "sign in / out" to be configurable. 
* remove sign out icon
* allow configuration for placement of popover
* allow custom menu items.

I think we're ready to merge now!  Thanks.

**Comment by gstroup** [comment]
Thanks!

**Comment by randyaskin** [comment]
No problem, thanks for doing all the work!

I'm trying to cutover from signInLabel / signOutLabel to our new standard for i18n, app-localize-behavior, but unfortunately it causes all the unit tests to fail - I need to work with Martin to figure out how we fix this, it's popped up in every component so far.

**Pull request merged**
